USE [GeradorDeTestes]
GO

/** Object:  Table [dbo].[TBDisciplina]    Script Date: 06/07/2023 18:18:05 **/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBDisciplina](
    [Id] [int] NOT NULL,
    [nome] [varchar](100) NOT NULL,
 CONSTRAINT [PK_TBDisciplina] PRIMARY KEY CLUSTERED 
(
    [Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
